### ISSUE TITLE
Adding Employee Hierarchy

### ISSUE THREAD

**Issue by djpirra** [sql-bi/Contoso-Data-Generator-V2#3]
Would be great if this could be augmented with one more dimension for Sales Structure containing the employee who made the sale (some sales could also be done online, without employee).

This way, more use cases could be tackled as well that depend on a employee hierarchy.

This dimension could be a hierarchy with:

Employee Id
Employee Name
Employee Region
Employee Country
Employee Position (Vendor, Regional Manager, Country Manager, Global Head of Sales)
Employee Manager Id

**Comment by marcosqlbi** [comment]
There could be tens of tables to add. Why not a generic employees table for HR (not just for sales), why not a BOM (Bill of Material), why not shipments, why not... you name it!
However, this is an open-source project. As such, anyone can create a derivative product and ask for a pull request if the contribution is generic and add value to the community - we will certainly consider it!
It is out of the scope of our investment to add (and maintain!) other tables to this project. At SQLBI, we use the result of the Contoso Data Generator for our demo files, and we add tables to specific data models whenever it is required for specific demos, but adding tables to the generic database is an additional cost of one or two orders of magnitude that we cannot justify for our internal use!
